USE tester;
SET foreign_key_checks = 0;

DROP TABLE servesOn;
DROP TABLE Bill; 
DROP TABLE Hearing; 
DROP TABLE JobSnapshot; 
DROP TABLE Action;  
DROP TABLE Video; 
DROP TABLE Video_ttml; 
DROP TABLE BillDiscussion;
DROP TABLE Committee; 
DROP TABLE Lobbyist;
DROP TABLE LobbyistEmployer;
DROP TABLE LobbyistEmployment;
DROP TABLE LobbyistDirectEmployment;
DROP TABLE LobbyingContracts;
DROP TABLE LobbyistRepresentation;
DROP TABLE LegislativeAuthorStaff;
DROP TABLE LobbyingFirm;
DROP TABLE CommitteeStaff;
DROP TABLE Analyst;
DROP TABLE StateAgencyRep;
DROP TABLE GeneralPublic;
DROP TABLE Term;
DROP TABLE Legislator;
DROP TABLE Person;
DROP TABLE Motion;
DROP TABLE votesOn;
DROP TABLE BillVersion;
DROP TABLE authors;
DROP TABLE attends;
DROP VIEW currentUtterance;
DROP TABLE Utterance;
DROP TABLE join_utrtag;
DROP TABLE Mention;
DROP TABLE TT_Editor;
DROP TABLE TT_Task;
DROP TABLE TT_TaskCompletion;
DROP TABLE tag;
DROP TABLE user;

SET foreign_key_checks = 1;
